version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run: echo "Instalando dependencias..."
      - run: npm install

  test:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run: echo "Ejecutando tests..."
      - run: npm test

  lint:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run: echo "Verificando estilo de código..."
      - run: npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
