  test:
    docker:
      - image: cimg/openjdk:17.0
    parallelism: 3
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas en paralelo
          command: |
            mkdir -p test-results
            TEST_FILES=$(circleci tests split --split-by=timings $(find src/test/java -name "*Test.java"))
            echo "$TEST_FILES" | xargs -I {} mvn -Dtest={} test
      - run:
          name: Copiar resultados de pruebas (si existen)
          command: |
            mkdir -p test-results
            if [ -d target/surefire-reports ]; then
              cp -r target/surefire-reports test-results/junit
            else
              echo "No se encontraron reportes de pruebas en este contenedor."
            fi
      - store_test_results:
          path: test-results
