version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Compilar el proyecto
          command: mvn clean compile

  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas
          command: mvn test

  package:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Empaquetar la aplicación
          command: mvn package

workflows:
  version: 2
  build_test_package:
    jobs:
      - build
      - test:
          requires:
            - build
      - package:
          requires:
            - test
